sudo: required
services:
 - docker
 
before_install:
 - docker build -t houssem01/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run houssem01/react-test npm test -- --coverage

after_success:
 - docker build -t houssem01/multi-client ./client
 - docker build -t houssem01/multi-nginx ./nginx
 - docker build -t houssem01/multi-server ./server
 - docker build -t houssem01/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
 # Take the images and push them to docker hub
 - docker push houssem01/multi-client
 - docker push houssem01/multi-nginx
 - docker push houssem01/multi-server
 - docker push houssem01/multi-worker

deploy:
 provider: elasticbeanstalk
 region: eu-west-1
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-eu-west-1-343962726333
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
 